### ISSUE TITLE
Infobox not responsive

### ISSUE THREAD

**Issue by AndyFou** [OSWINDS/TweetFix#10]
![image](https://cloud.githubusercontent.com/assets/8682216/18619706/426e65d6-7e0c-11e6-8fbc-dc1c3390a5f7.png)

![image](https://cloud.githubusercontent.com/assets/8682216/18619707/525060b2-7e0c-11e6-92e0-c180db3a03aa.png)

**Comment by kplatis** [comment]
Fixed it. Check new branch "bug_fixing" in Djokovic.html

**Comment by AndyFou** [comment]
Cool, well done! I like it!
Do you think we should consider making the infobox a little bit smaller, now that every info is on a different line?
