### ISSUE TITLE
Maybe add an info icon after each title, to explain what every chart is about?

### ISSUE THREAD

**Issue by AndyFou** [OSWINDS/TweetFix#20]
For example: 
![screen shot 2016-09-22 at 11 15 06 am](https://cloud.githubusercontent.com/assets/8682216/18741078/ded1b850-80b5-11e6-9616-bcf395f4f488.png)

**Comment by kplatis** [comment]
Done and pushed it. Check general.html

**Comment by AndyFou** [comment]
Awesome! Now we have to add one in every chart.
