### ISSUE TITLE
Change order of menu

### ISSUE THREAD

**Issue by AndyFou** [OSWINDS/TweetFix#7]
Change to:
Home --> About --> Cases --> Lexicon

OR 

Home --> Cases --> Lexicon --> About 

?

**Comment by AndyFou** [comment]
I would suggest the first order, because this page is part of a project, so it is important information (I think) !

**Comment by kplatis** [comment]
I vote for the first as you said cause Cases is more important that "About".

**Comment by kplatis** [comment]
Changed it. Check new branch "bug_fixing"

**Comment by AndyFou** [comment]
In pages "Case --> General" and "Lexicon" the order is not changed.

**Comment by AndyFou** [comment]
Fixed in branch "bug_fixing"
